# Site settings
title: 2015M217
email: colliand@math.ubc.ca
description: > # this means to ignore newlines until "baseurl:"
 
baseurl: "/2015M217" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: colliand
# github_username:  colliand

# Build settings
markdown: kramdown
timezone: America/Vancouver



#disqus widget
disqus:
  shortname: 'colliand'
  count: 5